name: Deploy to AWS
on:
  push:
    branches: [ "production" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mywarehome-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Docker 네트워크 생성
            docker network create myme-network || true
            
            # 기존 컨테이너 중지 및 삭제
            docker stop backend-container || true
            docker rm backend-container || true
            
            # 기존 이미지 삭제
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/mywarehome-backend:latest || true

            # 최신 이미지 pull
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mywarehome-backend:latest
            
            # 새 컨테이너 실행
            docker run -d \
              --name backend-container \
              --network myme-network \
              -p 8080:8080 \
              -e DB_URL=${{ secrets.DB_URL }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/mywarehome-backend:latest